### ISSUE TITLE
Pseudo-element `::-webkit-slider-thumb` is not working with interactive states

### ISSUE THREAD

**Issue by GomezIvann** [chromaui/storybook-addon-pseudo-states#98] opened 2023-11-28 13:50 UTC
We have a React component with the following selector: `::-webkit-slider-thumb:active`. The method `insertRule` fails to parser this rule:

![image](https://github.com/chromaui/storybook-addon-pseudo-states/assets/44321109/5261840c-6d7b-4156-9bb2-47c0d867de54)

This issue happens every time you concatenate a webkit pseudo-element with a pseudo-class. The problem is that the rest of the stories stop working whenever this error is thrown because they cannot load their respective styles.

**Comment by m-akinc** [comment] 2024-02-10 00:27
Duplicate of #37

**Comment by m-akinc** [comment] 2024-03-10 22:51
Issue should be marked closed as fixed.

**Closed as completed** 2024-03-12 08:15 UTC
